spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teacherxiangmu?serverTimezone=Asia/Shanghai
    # 数据库用户名&密码：
    username: root
    password: wuyuanjian0

server:
  port: 80